# Generated by Django 4.2.5 on 2023-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Designer'), (2, 'Customer'), (3, 'Architect')], null=True),
        ),
    ]
