# Generated by Django 4.2.5 on 2023-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='designer_description',
            field=models.TextField(null=True),
        ),
    ]
