# Generated by Django 4.2.5 on 2023-10-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_designer_designer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='offical_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
