# Generated by Django 4.2.5 on 2023-10-27 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_designer_experience_designer_offical_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projectimages/')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.designer')),
            ],
            options={
                'verbose_name': 'Office Image',
                'verbose_name_plural': 'Office Images',
            },
        ),
    ]
