# Generated by Django 4.2.5 on 2023-10-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_officeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
    ]
