# Generated by Django 4.2.5 on 2023-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_designer_facebook_link_designer_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
