# Generated by Django 4.2.5 on 2023-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_alter_designer_designer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='designer',
            name='designer_slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
