# Generated by Django 4.2.5 on 2023-12-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_alter_designer_designer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
