# Generated by Django 4.2.5 on 2023-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0008_alter_designer_designer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='offical_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
