# Generated by Django 4.2.5 on 2023-10-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_remove_checklist_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designer_checklist', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
