# Generated by Django 4.2.5 on 2023-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='project_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='foodimages'),
        ),
        migrations.AddField(
            model_name='category',
            name='property_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
