# Generated by Django 4.2.5 on 2023-11-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolioitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project_created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
