# Generated by Django 4.2.5 on 2023-12-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0001_initial'),
        ('portfolio', '0003_category_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architect_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('property_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='foodimages')),
                ('project_created_at', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('project_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architects.architect')),
            ],
            options={
                'verbose_name': 'Architect_category',
                'verbose_name_plural': 'Architect_categories',
            },
        ),
        migrations.CreateModel(
            name='Architect_PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foodimages')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architects.architect')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_portfolioitems', to='portfolio.architect_category')),
            ],
        ),
    ]
