# Generated by Django 4.2.5 on 2023-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_architect_category_architect_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect_portfolioitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='architect_portfolioitem',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
