# Generated by Django 4.2.5 on 2023-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_category',
            field=models.IntegerField(choices=[(1, 'Interior designer'), (2, 'Architect'), (3, 'Property ')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='customer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
