# Generated by Django 4.2.5 on 2023-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_testimonial_client_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_photo', models.ImageField(blank=True, null=True, upload_to='client_photos')),
                ('Ad_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
